const Pfas = [
  {
    pfaName: "STANBIC IBTC PENSION MANAGERS LIMITED",
    pfaCode: 21,
    pfc: "63650e0efcf27d12b5441df2",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    pfaName: "PREMIUM PENSION LIMITED",
    pfaCode: 22,
    pfc: "63650e0efcf27d12b5441df2",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    pfaName: "LEADWAY PENSURE PFA LIMITED",
    pfaCode: 23,
    pfc: "63650e0efcf27d12b5441df2",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    pfaName: "SIGMA PENSIONS LIMITED",
    pfaCode: 24,
    pfc: "63650e0efcf27d12b5441df2",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    pfaName: "PENSIONS ALLIANCE LIMITED",
    pfaCode: 25,
    pfc: "63650e0efcf27d12b5441df2",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    pfaName: "ARM PENSION MANAGERS (PFA) LIMITED",
    pfaCode: 26,
    pfc: "63650e0efcf27d12b5441df2",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    pfaName: "TRUSTFUND PENSIONS PLC",
    pfaCode: 28,
    pfc: "63650e0efcf27d12b5441df2",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    pfaName: "FIRST GUARANTEE PENSION LIMITED",
    pfaCode: 29,
    pfc: "63650e0efcf27d12b5441df2",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    pfaName: "LEGACY PENSION MANAGERS LIMITED (PFA)",
    pfaCode: 30,
    pfc: "63650e0efcf27d12b5441df2",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    pfaName: "NLPC PENSION FUND ADMINISTRATORS LIMITED",
    pfaCode: 31,
    pfc: "63650e0efcf27d12b5441df2",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    pfaName: "CRUSADERSTERLING PENSIONS LIMITED",
    pfaCode: 32,
    pfc: "63650f1dfcf27d12b5441df3",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    pfaName: "AIICO PENSION MANAGERS LIMITED",
    pfaCode: 33,
    pfc: "63650f1dfcf27d12b5441df3",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    pfaName: "OAK PENSIONS LIMITED",
    pfaCode: 34,
    pfc: "63650f1dfcf27d12b5441df3",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    pfaName: "AXA MANSARD PENSIONS LIMITED",
    pfaCode: 35,
    pfc: "63650f1dfcf27d12b5441df3",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    pfaName: "IEI-ANCHOR PENSION MANAGERS LIMITED",
    pfaCode: 36,
    pfc: "63650f1dfcf27d12b5441df3",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    pfaName: "APT PENSION FUNDS MANAGERS LIMITED",
    pfaCode: 37,
    pfc: "63650f1dfcf27d12b5441df3",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    pfaName: "FUTURE UNITY GLANVILLS PENSIONS LIMITED",
    pfaCode: 42,
    pfc: "63650f1dfcf27d12b5441df3",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    pfaName: "FIDELITY PENSION MANAGERS LIMITED",
    pfaCode: 43,
    pfc: "63650f1dfcf27d12b5441df3",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    pfaName: "INVESTMENT ONE PENSION MANAGERS LIMITED",
    pfaCode: 40,
    pfc: "63650f1dfcf27d12b5441df3",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    pfaName: "CITI TRUST PENSION FUND MANAGERS LIMITED",
    pfaCode: 44,
    pfc: "63650f1dfcf27d12b5441df3",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    pfaName: "IGI PENSION MANAGERS LIMITED",
    pfaCode: 46,
    pfc: "63650f1dfcf27d12b5441df3",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
];

module.exports = Pfas;
