const States = [
  {
    stateName: "ABIA",
    stateCode: "01",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "ADAMAWA",
    stateCode: "02",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "AKWA IBOM",
    stateCode: "03",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "ANAMBRA",
    stateCode: "04",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "BAUCHI",
    stateCode: "05",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "BAYELSA",
    stateCode: "06",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "BENUE",
    stateCode: "07",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "BORNO",
    stateCode: "08",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "CROSS RIVER",
    stateCode: "09",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "DELTA",
    stateCode: "10",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "EBONYI",
    stateCode: "11",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "EDO",
    stateCode: "12",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "EKITI",
    stateCode: "13",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "ENUGU",
    stateCode: "14",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "FCT",
    stateCode: "37",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "GOMBE",
    stateCode: "15",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "IMO",
    stateCode: "16",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "JIGAWA",
    stateCode: "17",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "KADUNA",
    stateCode: "18",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "KANO",
    stateCode: "19",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "KASTINA",
    stateCode: "20",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "KEBBI",
    stateCode: "21",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "KOGI",
    stateCode: "22",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "KWARA",
    stateCode: "23",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "LAGOS",
    stateCode: "24",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "NASSARAWA",
    stateCode: "25",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "NIGER",
    stateCode: "26",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "OGUN",
    stateCode: "27",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "ONDO",
    stateCode: "28",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "OSUN",
    stateCode: "29",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "OYO",
    stateCode: "30",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "PLATEAU",
    stateCode: "31",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "RIVERS",
    stateCode: "32",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "SOKOTO",
    stateCode: "33",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "TARABA",
    stateCode: "34",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "YOBE",
    stateCode: "35",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "ZAMFARA",
    stateCode: "36",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
  {
    stateName: "OUTSIDE NIGERIA",
    stateCode: "38",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
    deleted: false,
  },
];

module.exports = States;
